lista = input().split(' ')
a = int(lista[0])
b = int(lista[1])
c = float(lista[2])
lista2 = input().split(' ')
d = int(lista2[0])
e = int(lista2[1])
f = float(lista2[2])
total = (b * c) + (e * f)
print('VALOR A PAGAR: R$ {:.2f}'.format(total))
