lista = input().split(' ')
A = int(lista[0])
B = int(lista[1])
C = int(lista[2])
maiorAB = int((A + B + abs(A - B)) / 2)
maior = int((maiorAB + C + abs(maiorAB - C)) / 2)
print('{} eh o maior'.format(maior))
